### ISSUE TITLE
Add mobile "preview" for large screens

### ISSUE THREAD

**Issue by SteveBarnett** [universalcore/unicore-cms-mama#11]
Snippet to use:

``` css
/* Mobile "preview" for large screens */

    @media screen and (min-width: 1024px) { 
        html {
            background-color: #333;
        }
        body {
            max-width: 320px;
            margin: 0 auto;
        }
    }
```
